name: default
channels:
- conda-forge
- bioconda
- nodefaults
dependencies:
- python >=3.13.5,<3.14
- numpy >=2.3.2,<3
- notebook >=7.4.5,<8
- jupyterlab >=4.4.5,<5
- fastqc >=0.12.1,<0.13
- pandas >=2.3.1,<3
- scipy 1.15.1.*
- pip
- pip:
  - pandas>=2.3.1, <3
