[workspace]
authors = ["jennmald <jmaldonad@bnl.gov>"]
channels = ["conda-forge", "bioconda"]
name = "example"
platforms = ["osx-arm64","linux-64", "win-64"]
version = "0.1.0"

[activation.env]
MY_ENV_VAR = "Hello, Pixi!"

[tasks]
lab = { cmd = "jupyter lab --notebook-dir=." }
hello = { cmd = "echo 'hello world'"}
greet = { cmd = 'echo "Hello, {{ name }}!"', args = ["name"] }
greet-YOUR_NAME = [{ task = "greet", args = ["YOUR_NAME"] }]
start = { args = ["name"], depends-on = [{ task = "hello" }, { task = "greet", args = ["{{ name }}"] }] }
print-env = { cmd = "echo $MY_ENV_VAR" } 

[dependencies]
python = ">=3.13.5,<3.14"
numpy = ">=2.3.2,<3"
notebook = ">=7.4.5,<8"
jupyterlab = ">=4.4.5,<5"
fastqc = ">=0.12.1,<0.13"
pandas = ">=2.3.1,<3"
scipy = "1.15.1.*"

[feature.dev.dependencies]
pre-commit = ">=4.3.0,<5"

[environments]
dev = ["dev"]
test = { features = ["test"], solve-group = "group1" }
format = { features = ["format"], no-default-feature = true }
default = { solve-group = "group1" }

[pypi-dependencies]
pandas = ">=2.3.1, <3"

[feature.test.pypi-dependencies]
pytest = { git = "https://github.com/pytest-dev/pytest", tag = "8.3.1" }

[feature.format.dependencies]
ruff = "*"

[feature.format.tasks]
fmt = "ruff --version"
